name: Actions Workflow
on:
  - push
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      -  name: list files and folders
         run: |
           pwd
           ls -a
      -name: checkout
        uses: actions/checkout@v1
      - name: list files and folders and checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-great: "Marwen"
      - name: log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
